# Generated by Django 5.2.17 on 2026-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_alter_experience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(default='https://ik.imagekit.io/hefciv25h/portfolio/placeholder.jpg'),
        ),
    ]
