# Generated by Django 5.2.17 on 2026-09-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(default='https://github.com/adpsxx'),
        ),
    ]
